# Generated by Django 5.2 on 2026-02-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagen_url',
            field=models.URLField(max_length=500, verbose_name='Imagen (URL)'),
        ),
    ]
