# Generated by Django 5.2 on 2026-02-19 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidatour',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='lemonsqueezy_variant_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_adulto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_nino',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('lemonsqueezy', 'Lemon Squeezy'), ('paypal', 'PayPal')], max_length=20)),
                ('estado', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', max_length=20)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('checkout_url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.reserva')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
