# Generated by Django 5.2 on 2026-02-20 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salidatour_hora_tour_lemonsqueezy_variant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_tours/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción corta de la foto', max_length=255)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.tour')),
            ],
        ),
    ]
