# Generated by Codex on 2026-02-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_destino_descripcion_alter_destino_imagen_url"),
        ("core", "0002_salidatour_hora_alter_reserva_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("proveedor", models.CharField(choices=[("stripe", "Stripe"), ("paypal", "PayPal")], max_length=20)),
                ("estado", models.CharField(choices=[("created", "Created"), ("approved", "Approved"), ("paid", "Paid"), ("failed", "Failed"), ("canceled", "Canceled")], default="created", max_length=20)),
                ("moneda", models.CharField(default="USD", max_length=3)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("checkout_url", models.URLField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("reserva", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pagos", to="core.reserva")),
            ],
            options={
                "ordering": ("-creado_en",),
            },
        ),
    ]
