# Generated by Django 5.2 on 2026-02-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='O pega el enlace de Drive/Photos/Internet', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una foto local (desde tu PC)', null=True, upload_to='galeria_tours/'),
        ),
    ]
