# Generated by Codex on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="proveedor",
            field=models.CharField(
                choices=[("lemonsqueezy", "Lemon Squeezy"), ("paypal", "PayPal")],
                max_length=20,
            ),
        ),
    ]
