# Generated by Django 5.2 on 2026-02-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galeria_imagen_url_alter_galeria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='descripcion',
        ),
    ]
