# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_pago_proveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="lemonsqueezy_variant_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
