# Generated by Django 5.2.8 on 2026-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tour_lemonsqueezy_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='precio_adulto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_nino',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
