# Generated by Django 5.2 on 2026-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_agencia',
            field=models.BooleanField(default=False, help_text='Si se activa, el usuario podrá bloquear reservas por 15 días', verbose_name='Es agencia de tours'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('bloqueada_por_agencia', 'Bloqueada por Agencia')], default='pendiente', max_length=30),
        ),
    ]
