# Generated by Django 5.2 on 2026-02-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_is_agencia_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='archivo_agencia',
            field=models.FileField(blank=True, null=True, upload_to='agencia_vouchers/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_agencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='limite_pago_agencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
