# Generated by Django 5.2 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_reserva_archivo_agencia_reserva_codigo_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="proveedor",
            field=models.CharField(
                choices=[
                    ("lemonsqueezy", "Lemon Squeezy"),
                    ("paypal", "PayPal"),
                    ("cash", "Efectivo"),
                ],
                max_length=20,
            ),
        ),
    ]
