# Generated by Django 5.2 on 2026-02-21 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reserva_archivo_agencia_reserva_codigo_agencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidatour',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
