# Generated by Django 5.2 on 2026-02-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reserva_creado_por_salidatour_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='proveedor',
            field=models.CharField(choices=[('lemonsqueezy', 'Lemon Squeezy'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], max_length=20),
        ),
    ]
