# Generated by Django 5.2 on 2026-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pago_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hora_turno_1',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Turno 1'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hora_turno_2',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Turno 2'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=16),
        ),
    ]
