# Generated by Django 5.2 on 2026-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tour_hora_turno_1_tour_hora_turno_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duracion',
            field=models.CharField(default='1 día', help_text="Ej: '4 horas', 'Día completo', '2 días'.", max_length=50),
        ),
    ]
