# Generated by Django 5.2 on 2026-02-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tour_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidatour',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='salidatour',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 4 horas, Medio día, etc.', max_length=100, null=True, verbose_name='Duración del tour'),
        ),
    ]
