# Generated by Django 5.2 on 2026-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_salidatour_cupo_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidatour',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: Medio día (4 horas)', max_length=100, null=True, verbose_name='Duración'),
        ),
    ]
